import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/navbar/page'
const inter = Inter({ subsets: ['latin'] })
import { Suspense } from 'react'

export const metadata = {
  title: 'Appwrite Auth',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Suspense fallback={<p>Loading </p>}>
        <Navbar />
      </Suspense>
        {children}
      </body>
    </html>
  )
}
